name: Push to prod instances gen3 plotter*
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to plotter1-gen3
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: offkai
          containerAppName: plotter1-gen3
          resourceGroup: plotter
          imageToBuild: offkai.azurecr.io/plotter:${{ github.sha }}

      - name: Build and deploy to plotter2-gen3
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: offkai
          containerAppName: plotter2-gen3
          resourceGroup: plotter
          imageToBuild: offkai.azurecr.io/plotter:${{ github.sha }}
      
      - name: Build and deploy to plotter3-gen3
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: offkai
          containerAppName: plotter3-gen3
          resourceGroup: plotter
          imageToBuild: offkai.azurecr.io/plotter:${{ github.sha }}
